# Generated by Django 4.2.30 on 2026-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
