# Generated by Django 4.2.30 on 2026-08-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('learning', '0003_lessonprogress_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.course')),
            ],
            options={
                'verbose_name': 'Розділ курсу',
                'verbose_name_plural': 'Розділи курсу',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.coursesection')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Теми',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Документ'), ('ppt', 'Презентація'), ('link', 'Посилання'), ('video', 'Відео')], default='pdf', max_length=16)),
                ('meta', models.CharField(blank=True, max_length=128)),
                ('url', models.CharField(blank=True, default='#', max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.coursetopic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.coursetopic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не розпочато'), ('in_progress', 'В роботі'), ('done', 'Пройдено')], default='not_started', max_length=20)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='learning.enrollment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='learning.coursetopic')),
            ],
            options={
                'unique_together': {('enrollment', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не розпочато'), ('in_progress', 'В роботі'), ('submitted', 'На перевірці'), ('reviewed', 'Перевірено')], default='not_started', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=16)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='learning.topicassignment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_progress', to='learning.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'assignment')},
            },
        ),
    ]
