# Generated by Django 4.2.30 on 2026-08-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_cabinetsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentprogress',
            name='hw_status',
            field=models.CharField(blank=True, choices=[('done', 'Виконано'), ('partial', 'Частково'), ('not_done', 'Не виконано')], max_length=16),
        ),
        migrations.AddField(
            model_name='topicassignment',
            name='due_label',
            field=models.CharField(blank=True, default='До наступного заняття', max_length=128),
        ),
        migrations.AlterField(
            model_name='topicmaterial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Документ'), ('ppt', 'Презентація'), ('zip', 'ZIP'), ('link', 'Посилання'), ('video', 'Відео')], default='pdf', max_length=16),
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Присутній'), ('late', 'Запізнився'), ('absent', 'Відсутній')], default='present', max_length=16)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='learning.enrollment')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rows', to='learning.scheduleslot')),
            ],
            options={
                'verbose_name': 'Відвідуваність',
                'verbose_name_plural': 'Відвідуваність',
                'ordering': ['-date', 'id'],
                'unique_together': {('enrollment', 'slot', 'date')},
            },
        ),
    ]
