# Generated by Django 4.2.30 on 2026-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_teacher_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexception',
            name='status',
            field=models.CharField(choices=[('held', 'Проведено'), ('cancelled', 'Скасовано'), ('teacher_fault', 'Скасовано з вини викладача')], default='cancelled', max_length=16),
        ),
    ]
