# Generated by Django 4.2.30 on 2026-08-14 11:22

from django.db import migrations, models


def forwards(apps, schema_editor):
    ScheduleException = apps.get_model("learning", "ScheduleException")
    ScheduleException.objects.filter(status="teacher_fault").update(status="compensated")


def backwards(apps, schema_editor):
    ScheduleException = apps.get_model("learning", "ScheduleException")
    ScheduleException.objects.filter(status="compensated").update(status="teacher_fault")


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_lesson_exception_statuses"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="scheduleexception",
            name="status",
            field=models.CharField(
                choices=[
                    ("held", "Проведено"),
                    ("cancelled", "Скасовано"),
                    ("compensated", "Скасовано з компенсацією"),
                ],
                default="cancelled",
                max_length=16,
            ),
        ),
    ]
