# Generated by Django 4.2.30 on 2026-08-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('card_description', models.TextField(blank=True)),
                ('card_image', models.CharField(blank=True, max_length=512)),
                ('age_range', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=512)),
                ('video', models.CharField(blank=True, max_length=512)),
                ('suitable', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=64)),
                ('lessons_label', models.CharField(max_length=64)),
                ('lessons_count', models.PositiveIntegerField()),
                ('price_per_lesson', models.PositiveIntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ['order', 'lessons_count'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Соцмережа',
                'verbose_name_plural': 'Соцмережі',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Відео-відгук',
                'verbose_name_plural': 'Відео-відгуки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='catalog.course')),
            ],
            options={
                'verbose_name': 'Для кого курс',
                'verbose_name_plural': 'Для кого курс',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoursePlanLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_levels', to='catalog.course')),
            ],
            options={
                'verbose_name': 'План рівня',
                'verbose_name_plural': 'Плани рівнів',
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'level')},
            },
        ),
    ]
