from django.urls import path

from .api_views import MyEnrollmentDetailView, MyEnrollmentsView, MyScheduleView, ToggleLessonView
from .staff_views import (
    OfficeCourseAccessView,
    OfficeCourseDetailView,
    OfficeCoursesView,
    OfficeHomeView,
    OfficeLookupsView,
    OfficeMaterialDuplicateView,
    OfficeMaterialView,
    OfficeMaterialsBulkView,
    OfficePeopleView,
    OfficePersonDetailView,
    OfficeReorderView,
    OfficeScheduleView,
    OfficeSectionView,
    OfficeTopicView,
    OfficeTransactionDetailView,
    OfficeTransactionsView,
)
from .teacher_views import (
    MySyncView,
    TeacherAddAssignmentView,
    TeacherAssignmentUpdateView,
    TeacherAttendanceView,
    TeacherCourseDetailView,
    TeacherCoursesView,
    TeacherGradeView,
    TeacherLessonView,
    TeacherNotesView,
    TeacherScheduleExceptionView,
    TeacherScheduleView,
    TeacherStudentDetailView,
    TeacherStudentMaterialDetailView,
    TeacherStudentMaterialView,
    TeacherStudentsView,
    TeacherTopicStatusView,
)
from apps.catalog.listing_views import (
    OfficeListingCourseView,
    OfficeListingFaqView,
    OfficeListingPricingView,
    OfficeListingReviewView,
    OfficeListingSiteView,
    OfficeListingSocialView,
    OfficeListingVideoView,
    OfficeListingView,
)

urlpatterns = [
    path("my/enrollments", MyEnrollmentsView.as_view(), name="my-enrollments"),
    path("my/enrollments/", MyEnrollmentsView.as_view()),
    path(
        "my/enrollments/<slug:course_id>",
        MyEnrollmentDetailView.as_view(),
        name="my-enrollment-detail",
    ),
    path(
        "my/enrollments/<slug:course_id>/",
        MyEnrollmentDetailView.as_view(),
    ),
    path("my/schedule", MyScheduleView.as_view(), name="my-schedule"),
    path("my/schedule/", MyScheduleView.as_view()),
    path("my/sync", MySyncView.as_view(), name="my-sync"),
    path("my/sync/", MySyncView.as_view()),
    path("my/lessons/<int:pk>/toggle", ToggleLessonView.as_view(), name="toggle-lesson"),
    path("my/lessons/<int:pk>/toggle/", ToggleLessonView.as_view()),
    path("teacher/students", TeacherStudentsView.as_view(), name="teacher-students"),
    path("teacher/students/", TeacherStudentsView.as_view()),
    path("teacher/students/<int:pk>", TeacherStudentDetailView.as_view(), name="teacher-student"),
    path("teacher/students/<int:pk>/", TeacherStudentDetailView.as_view()),
    path(
        "teacher/enrollments/<int:enrollment_id>/topics/<int:topic_id>",
        TeacherTopicStatusView.as_view(),
        name="teacher-topic-status",
    ),
    path(
        "teacher/enrollments/<int:enrollment_id>/topics/<int:topic_id>/",
        TeacherTopicStatusView.as_view(),
    ),
    path(
        "teacher/topics/<int:topic_id>/assignments",
        TeacherAddAssignmentView.as_view(),
        name="teacher-add-assignment",
    ),
    path(
        "teacher/topics/<int:topic_id>/assignments/",
        TeacherAddAssignmentView.as_view(),
    ),
    path(
        "teacher/enrollments/<int:enrollment_id>/assignments/<int:assignment_id>",
        TeacherGradeView.as_view(),
        name="teacher-grade",
    ),
    path(
        "teacher/enrollments/<int:enrollment_id>/assignments/<int:assignment_id>/",
        TeacherGradeView.as_view(),
    ),
    path("teacher/schedule", TeacherScheduleView.as_view(), name="teacher-schedule"),
    path("teacher/schedule/", TeacherScheduleView.as_view()),
    path(
        "teacher/schedule/exceptions",
        TeacherScheduleExceptionView.as_view(),
        name="teacher-schedule-exceptions",
    ),
    path("teacher/schedule/exceptions/", TeacherScheduleExceptionView.as_view()),
    path(
        "teacher/schedule/exceptions/<int:pk>",
        TeacherScheduleExceptionView.as_view(),
        name="teacher-schedule-exception",
    ),
    path("teacher/schedule/exceptions/<int:pk>/", TeacherScheduleExceptionView.as_view()),
    path("teacher/courses", TeacherCoursesView.as_view(), name="teacher-courses"),
    path("teacher/courses/", TeacherCoursesView.as_view()),
    path("teacher/courses/<slug:pk>", TeacherCourseDetailView.as_view(), name="teacher-course"),
    path("teacher/courses/<slug:pk>/", TeacherCourseDetailView.as_view()),
    path(
        "teacher/enrollments/<int:enrollment_id>/topics/<int:topic_id>/materials",
        TeacherStudentMaterialView.as_view(),
        name="teacher-student-material",
    ),
    path(
        "teacher/enrollments/<int:enrollment_id>/topics/<int:topic_id>/materials/",
        TeacherStudentMaterialView.as_view(),
    ),
    path(
        "teacher/student-materials/<int:pk>",
        TeacherStudentMaterialDetailView.as_view(),
        name="teacher-student-material-detail",
    ),
    path(
        "teacher/student-materials/<int:pk>/",
        TeacherStudentMaterialDetailView.as_view(),
    ),
    path(
        "teacher/assignments/<int:assignment_id>",
        TeacherAssignmentUpdateView.as_view(),
        name="teacher-assignment",
    ),
    path(
        "teacher/assignments/<int:assignment_id>/",
        TeacherAssignmentUpdateView.as_view(),
    ),
    path(
        "teacher/enrollments/<int:enrollment_id>/notes",
        TeacherNotesView.as_view(),
        name="teacher-notes",
    ),
    path(
        "teacher/enrollments/<int:enrollment_id>/notes/",
        TeacherNotesView.as_view(),
    ),
    path("teacher/attendance", TeacherAttendanceView.as_view(), name="teacher-attendance"),
    path("teacher/attendance/", TeacherAttendanceView.as_view()),
    path(
        "teacher/lessons/<int:slot_id>/<str:day>",
        TeacherLessonView.as_view(),
        name="teacher-lesson",
    ),
    path(
        "teacher/lessons/<int:slot_id>/<str:day>/",
        TeacherLessonView.as_view(),
    ),
    path("office/home", OfficeHomeView.as_view(), name="office-home"),
    path("office/home/", OfficeHomeView.as_view()),
    path("office/lookups", OfficeLookupsView.as_view(), name="office-lookups"),
    path("office/lookups/", OfficeLookupsView.as_view()),
    path("office/courses", OfficeCoursesView.as_view(), name="office-courses"),
    path("office/courses/", OfficeCoursesView.as_view()),
    path("office/courses/<slug:pk>", OfficeCourseDetailView.as_view(), name="office-course"),
    path("office/courses/<slug:pk>/", OfficeCourseDetailView.as_view()),
    path(
        "office/courses/<slug:pk>/access",
        OfficeCourseAccessView.as_view(),
        name="office-course-access",
    ),
    path("office/courses/<slug:pk>/access/", OfficeCourseAccessView.as_view()),
    path(
        "office/courses/<slug:pk>/access/<int:user_id>",
        OfficeCourseAccessView.as_view(),
        name="office-course-access-user",
    ),
    path("office/courses/<slug:pk>/access/<int:user_id>/", OfficeCourseAccessView.as_view()),
    path(
        "office/courses/<slug:pk>/sections",
        OfficeSectionView.as_view(),
        name="office-course-sections",
    ),
    path("office/courses/<slug:pk>/sections/", OfficeSectionView.as_view()),
    path(
        "office/sections/<int:section_id>",
        OfficeSectionView.as_view(),
        name="office-section",
    ),
    path("office/sections/<int:section_id>/", OfficeSectionView.as_view()),
    path(
        "office/sections/<int:section_id>/topics",
        OfficeTopicView.as_view(),
        name="office-section-topics",
    ),
    path("office/sections/<int:section_id>/topics/", OfficeTopicView.as_view()),
    path("office/topics/<int:topic_id>", OfficeTopicView.as_view(), name="office-topic"),
    path("office/topics/<int:topic_id>/", OfficeTopicView.as_view()),
    path(
        "office/topics/<int:topic_id>/materials",
        OfficeMaterialView.as_view(),
        name="office-topic-materials",
    ),
    path("office/topics/<int:topic_id>/materials/", OfficeMaterialView.as_view()),
    path("office/materials/<int:pk>", OfficeMaterialView.as_view(), name="office-material"),
    path("office/materials/<int:pk>/", OfficeMaterialView.as_view()),
    path(
        "office/materials/<int:pk>/duplicate",
        OfficeMaterialDuplicateView.as_view(),
        name="office-material-duplicate",
    ),
    path("office/materials/<int:pk>/duplicate/", OfficeMaterialDuplicateView.as_view()),
    path("office/materials/bulk", OfficeMaterialsBulkView.as_view(), name="office-materials-bulk"),
    path("office/materials/bulk/", OfficeMaterialsBulkView.as_view()),
    path(
        "office/courses/<slug:pk>/reorder",
        OfficeReorderView.as_view(),
        name="office-course-reorder",
    ),
    path("office/courses/<slug:pk>/reorder/", OfficeReorderView.as_view()),
    path("office/people", OfficePeopleView.as_view(), name="office-people"),
    path("office/people/", OfficePeopleView.as_view()),
    path("office/people/<int:pk>", OfficePersonDetailView.as_view(), name="office-person"),
    path("office/people/<int:pk>/", OfficePersonDetailView.as_view()),
    path("office/schedule", OfficeScheduleView.as_view(), name="office-schedule"),
    path("office/schedule/", OfficeScheduleView.as_view()),
    path("office/schedule/<int:pk>", OfficeScheduleView.as_view(), name="office-schedule-slot"),
    path("office/schedule/<int:pk>/", OfficeScheduleView.as_view()),
    path("office/transactions", OfficeTransactionsView.as_view(), name="office-transactions"),
    path("office/transactions/", OfficeTransactionsView.as_view()),
    path(
        "office/transactions/<int:pk>",
        OfficeTransactionDetailView.as_view(),
        name="office-transaction",
    ),
    path("office/transactions/<int:pk>/", OfficeTransactionDetailView.as_view()),
    path("office/listing", OfficeListingView.as_view(), name="office-listing"),
    path("office/listing/", OfficeListingView.as_view()),
    path("office/listing/site", OfficeListingSiteView.as_view(), name="office-listing-site"),
    path("office/listing/site/", OfficeListingSiteView.as_view()),
    path(
        "office/listing/courses/<slug:pk>",
        OfficeListingCourseView.as_view(),
        name="office-listing-course",
    ),
    path("office/listing/courses/<slug:pk>/", OfficeListingCourseView.as_view()),
    path("office/listing/pricing", OfficeListingPricingView.as_view(), name="office-listing-pricing"),
    path("office/listing/pricing/", OfficeListingPricingView.as_view()),
    path(
        "office/listing/pricing/<slug:pk>",
        OfficeListingPricingView.as_view(),
        name="office-listing-pricing-item",
    ),
    path("office/listing/pricing/<slug:pk>/", OfficeListingPricingView.as_view()),
    path("office/listing/faq", OfficeListingFaqView.as_view(), name="office-listing-faq"),
    path("office/listing/faq/", OfficeListingFaqView.as_view()),
    path("office/listing/faq/<int:pk>", OfficeListingFaqView.as_view(), name="office-listing-faq-item"),
    path("office/listing/faq/<int:pk>/", OfficeListingFaqView.as_view()),
    path("office/listing/socials", OfficeListingSocialView.as_view(), name="office-listing-socials"),
    path("office/listing/socials/", OfficeListingSocialView.as_view()),
    path(
        "office/listing/socials/<slug:pk>",
        OfficeListingSocialView.as_view(),
        name="office-listing-social-item",
    ),
    path("office/listing/socials/<slug:pk>/", OfficeListingSocialView.as_view()),
    path("office/listing/videos", OfficeListingVideoView.as_view(), name="office-listing-videos"),
    path("office/listing/videos/", OfficeListingVideoView.as_view()),
    path(
        "office/listing/videos/<int:pk>",
        OfficeListingVideoView.as_view(),
        name="office-listing-video-item",
    ),
    path("office/listing/videos/<int:pk>/", OfficeListingVideoView.as_view()),
    path("office/listing/reviews", OfficeListingReviewView.as_view(), name="office-listing-reviews"),
    path("office/listing/reviews/", OfficeListingReviewView.as_view()),
    path(
        "office/listing/reviews/<int:pk>",
        OfficeListingReviewView.as_view(),
        name="office-listing-review-item",
    ),
    path("office/listing/reviews/<int:pk>/", OfficeListingReviewView.as_view()),
]
