# Generated by Django 4.2.30 on 2026-08-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.CharField(blank=True, max_length=16)),
                ('review', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.course')),
            ],
            options={
                'verbose_name': 'Текстовий відгук',
                'verbose_name_plural': 'Текстові відгуки',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
